disabled_rules:
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
  - nesting

opt_in_rules:
- untyped_error_in_catch
- unowned_variable_capture
- type_contents_order
- required_deinit
- optional_enum_case_matching
- legacy_multiple
- indentation_width
- flatmap_over_map_reduce
- file_name_no_space
- enum_case_associated_values_count
- contains_over_range_nil_comparison
- closure_parameter_position
- explicit_init
- pattern_matching_keywords
- colon
- anyobject_protocol
- array_init
- attributes
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- contains_over_first_not_nil
- convenience_type
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_count
- empty_string
- empty_xctest_method
- fallthrough
- fatal_error_message
- first_where
- force_unwrapping
- identical_operands
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- last_where
- legacy_random
- literal_expression_end_indentation
- lower_acl_than_parent
- modifier_order
- multiline_arguments
- multiline_arguments_brackets
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- nslocalizedstring_key
- number_separator
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- private_action
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- sorted_first_last
- static_operator
- strong_iboutlet
- switch_case_on_newline
- toggle_bool
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- xct_specific_matcher
- yoda_condition
- redundant_type_annotation
- trailing_newline
- control_statement
- syntactic_sugar
- statement_position
- trailing_semicolon
- return_arrow_whitespace
- opening_brace
- closing_brace
- weak_delegate
- let_var_whitespace
- empty_parameters
- identifier_name
- type_name
- for_where

#- conditional_returns_on_newline
#- strict_fileprivate
#- file_name
excluded:
- Carthage
- Pods
- {{cookiecutter.app_name}}Tests
- {{cookiecutter.app_name}}/Resources/Generated

force_unwrapping: error
trailing_semicolon: error
empty_count: error
closing_brace: error
opening_brace: error
return_arrow_whitespace: error
statement_position: error
colon: error
comma: error
force_cast: error
force_try:
  severity: error
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
type_body_length:
  warning: 200
  error: 250
trailing_comma:
  mandatory_comma: true
file_length:
  warning: 400
  error: 450
function_body_length:
  warning: 80
  error: 100
type_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
implicit_return:
   included: [closure]

identifier_name:
  excluded:
    - id
    - to
    - in
    - at
    - of
    - up
    
custom_rules:
  redundant_print_statements:
    name: "Redundant print statement"
    regex: "^\\s*(print|println|OSLog)\\(\\s*(.*)\\)"
    message: "Please don't use print() or any log statements exept printInDebug func"
    severity: error

warning_threshold: 15
reporter: "xcode"
